# Configuration for the ClickHouse cluster to be started
clickhouse:

  # default cluster name
  clusterName: cluster

  ## StatefulSet controller supports relax its ordering guarantees while preserving its uniqueness and identity guarantees. There are two valid pod management policies: OrderedReady and Parallel
  ## ref: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ##
  podManagementPolicy: Parallel

  ## StatefulSet controller supports automated updates. There are two valid update strategies: RollingUpdate and OnDelete
  ## ref: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets
  ##
  updateStrategy: RollingUpdate

  # User Configuration
  users:
    - username: default
      password: C1ickh0use
  # Port configuration, see https://clickhouse.tech/docs/en/interfaces/
  ports:
    # Port for the native CLI interface, see https://clickhouse.tech/docs/en/interfaces/tcp/
    native: 9000

    # Port for HTTP/REST interface, see https://clickhouse.tech/docs/en/interfaces/http/
    http: 8123

  # If no explicit configuration for PersistentVolumeClaims is defined with the replicas,
  # create new PersistentVolumeClaims with this storage class:
  defaultStorageClassName: default
  defaultStorageResourceRequest: 1Gi

  # Shart configuration, see https://clickhouse.tech/docs/en/operations/table_engines/distributed/
  shards:
    - name: shard0
      replicas:
        - name: shard0-replica0

  # ClickHouse server image configuration
  image: tceason/clickhouse-server:v21.1.3.32-stable
  imagePullPolicy: Always

  # By default, this helm chart will create a service for getting access to the cluster.
  # Using this configuration it is possible to adjust the service settings.
  service:
    # Should the service be created by the helm chart?
    enabled: true

    # Type of the service. Use ClusterIP for internal access, LoadBalancer for external access.
    type: ClusterIP

    # Define the loadBalancerIP if type is set to LoadBalancer and you want to request a special IP address.
    loadBalancerIP:

  ipv4: true
  ipv6: false

# zookeeper configuration
zookeeper:
  # internal - start single instance zookeeper with this helm chart (for development purposes)
  # external - use external available zookeeper servers (for production use)
  mode: internal

  # configuration for internal zookeeper instance
  internal:
    image: zookeeper:3.5
    imagePullPolicy: Always

  # configuration for external zookeeper cluster
  external:
    # list of external zookeeper instances
    instances:
      - host: zk-1
        port: 2181
