# zookeeper configuration
zookeeper:
  replicas: 3

  # configuration for zookeeper instance
  image: tceason/zookeeper:3.6.2
  imagePullPolicy: IfNotPresent

  resources:
    memory: "1Gi"
    cpu: "0.5"
