# This file is part of the ClickHouse Helm Chart
#    https://github.com/radondb/clickhouse-cluster-helm
#
# Copyright 2021 TCeason <tai_chong@foxmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if eq .Values.zookeeper.mode "internal" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defaultObjectName" . }}-zookeeper
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "defaultMatchLabels" $ | nindent 4 }}
    clickhouse/component: zookeeper
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defaultObjectName" . }}-zookeeper
  labels:
    {{- include "defaultLabels" . | nindent 4 }}
    clickhouse/component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "defaultMatchLabels" $ | nindent 6 }}
      clickhouse/component: zookeeper
  template:
    metadata:
      labels:
        {{- include "defaultMatchLabels" $ | nindent 8 }}
        clickhouse/component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ $.Values.zookeeper.internal.image }}
          imagePullPolicy: {{ $.Values.zookeeper.internal.imagePullPolicy }}
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
{{- end }}
